# Generated by Django 3.2.6 on 2022-09-06 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ews', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
