# Generated by Django 4.1.6 on 2023-04-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ews', '0003_emailalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailalert',
            name='target',
            field=models.CharField(max_length=50),
        ),
    ]
